title: Baird Langenbrunner
timezone: America/New_York_City
email: bairdlangenbrunner@gmail.com
author: Baird

theme_color: orange-light
syntax_highlighting: light
gradient_header: false
home_social_buttons: true
header_accent_bgcolor: false # line on front page same as background color

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  heyitsbaird
github_username:  bairdlangenbrunner
github_site_repo: swiss-cheese
linkedin_username:  bairdlangenbrunner

# Build settings
markdown: kramdown
#theme: jekyll-swiss
remote_theme: bairdlangenbrunner/swiss-cheese
plugins:
  - jekyll-feed
  - jemoji

include:
  - _pages

collections:
  - python
  - projects

collections:
  projects:
    output: true
    permalink: /:collection/:name
  python:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page-no-title
  - scope:
      path: ""
      type: projects
    values:
      layout: page-no-title
  - scope:
      path: ""
      type: python
    values:
      layout: page-no-title
  - scope:
      path: ""
      type: posts
    values:
      layout: post
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Build settings
markdown: kramdown
highlighter: rouge
